[package]
name = "lox"
version = "0.3.0-dev3"
edition = "2024"

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }

[profile.release]
lto = true